### PR TITLE
Fixed indeterministic stuff

### PR DESCRIPTION
**Pull request by mastercoder10**
- JobId is generated using a global counter in coda:jobId
- Date is now equal to the current block height. Jobs older than current.blockheight - job.date  >= certain value get removed.
- Check if a fact is valid when adding a coda job
- Adding jobs to coda works again, had some issues due to changes in schema

### CODE REVIEW

**Comment by wilcooo** [comment]
- I don't know whether the apply method is guaranteed to run directly after validating the same transaction; so the this.header might be set due to an unrelated transaction. And I highly doubt whether those methods are guaranteed to run during the same block on all nodes. This could still introduce inconsistencies when f.e.:
 1. on node A a transaction T gets validated -> this.header gets set
 2. A new block gets forged (still without the transaction T) -> blockheight increases
 3. on node B the transaction T gets validated -> this.header gets set here as well
 4. Transaction T gets applied in the next forged block, with inconsistent blockheights between nodes
and probably plenty more subtle ways involving multiple transactions

B.t.w. this is just me guessing how Lisk works. As far as I know, Lisk does not document or warn for the validate method to be purely functional. 😁

**Comment by mastercoder10** [comment]
@wilcooo I have updated it according to your suggestions. The method beforeBlockApply could possibly be refactored later on into two separate methods to make it more readable, one for removing the old jobs and the other for adjusting the block height.

**Comment by wilcooo** [comment]
implementation looks good now, just have some smaller comments
- removeOldJobs still exists on the CodaAddJobAsset, this is now redundant
- all those Lisk methods on Assets or Modules have context types, such as `BeforeBlockApplyContext`, I suggest using them (I might add all these during code cleanup)
- beforeBlockApply also has access to `block.header.height` (as could be suggested by TS when you use the applicable Context type :smile:), which could be used instead of reading, decoding & calculating it yourself
- Might have some more comments, but i have to get off at this train station

**Comment by wilcooo** [comment]
> I'm not sure how to

A code snippet says more than a thousand words

image

Heb het meteen maar gecommit

**Comment by mastercoder10** [comment]
> > I'm not sure how to
> 
> A code snippet says more than a thousand words
> 
> image
> 
> Heb het meteen maar gecommit

Ah nice, een heel stuk korter zo

**Review by wilcooo — APPROVED** [review]

**Pull request merged**
